[bin] dw: initial archive handling

diff --git a/scripts/dw b/scripts/dw
--- a/scripts/dw
+++ b/scripts/dw
@@ -1,5 +1,67 @@
 #!/bin/zsh
 
+extract(){
+    local remove_archive
+    local success
+    local file_name
+    local extract_dir
+    remove_archive=1
+    if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]
+    then
+            remove_archive=0
+            shift
+    fi
+    while (( $# > 0 ))
+    do
+            if [[ ! -f "$1" ]]
+            then
+                    echo "extract: '$1' is not a valid file" >&2
+                    shift
+                    continue
+            fi
+            success=0
+            file_name="$( basename "$1" )"
+            extract_dir="$( echo "${file_name}" | sed "s/\.${1##*.}//g" )"
+            case "${1}" in
+                    (*.tar.gz|*.tgz) [ -z ${commands}[pigz] ] && tar zxvf "${1}" || pigz -dc "${1}" | tar xv ;;
+                    (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "${1}" ;;
+                    (*.tar.xz|*.txz) tar --xz --help &> /dev/null && tar --xz -xvf "${1}" || xzcat "${1}" | tar xvf - ;;
+                    (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null && tar --lzma -xvf "${1}" || lzcat "${1}" | tar xvf - ;;
+                    (*.tar) tar xvf "${1}" ;;
+                    (*.gz) [ -z ${commands}[pigz] ] && gunzip "${1}" || pigz -d "${1}" ;;
+                    (*.bz2) bunzip2 "${1}" ;;
+                    (*.xz) unxz "${1}" ;;
+                    (*.lzma) unlzma "${1}" ;;
+                    (*.Z) uncompress "${1}" ;;
+                    (*.zip|*.war|*.jar|*.sublime-package) unzip "${1}" -d ${extract_dir} ;;
+                    (*.rar) unrar x -ad "${1}" ;;
+                    (*.7z) 7za x "${1}" ;;
+                    (*.deb) mkdir -p "${extract_dir}/control"
+                            mkdir -p "${extract_dir}/data"
+                            cd "$extract_dir"
+                            ar vx "../${1}" > /dev/null
+                            cd control
+                            tar xzvf ../control.tar.gz
+                            cd ../data
+                            tar xzvf ../data.tar.gz
+                            cd ..
+                            rm *.tar.gz debian-binary
+                            cd .. ;;
+                    (*) echo "extract: '${1}' cannot be extracted" >&2
+                            success=1  ;;
+            esac
+            (( success = ${success} > 0 ? ${success} : $? ))
+            (( ${success} == 0 )) && (( ${remove_archive} == 0 )) && rm "$1"
+            shift
+    done
+}
+
+handle_archive(){
+    cd "$1"
+    mkdir "${1%.*}"
+    extract --remove ./*
+}
+
 main(){
     case "$1" in
         c*) 
@@ -22,7 +84,7 @@ main(){
             local vid="$(readlink -f ${HOME}/vid/new/)"
 
             rmdir ${dw}/{img,archive} 2> /dev/null&
-            mkdir ${dw}/{img,archive}
+            mkdir ${dw}/{img,archive} 2> /dev/null&
 
             find ${dw}/ -maxdepth 1 -name "*.iso" \
                 -exec mv -n -t ${dw}/img {} +
@@ -34,6 +96,8 @@ main(){
                 ".*\.(flv|mp4|avi|mkv|mov|webm|wmv)$" -exec mv -vnt ${vid}/ {} +
             find ${dw}/ -maxdepth 1 -regextype posix-egrep -regex \
                 ".*\.(mp3|ogg|flac|wma|flac|alac|dsf|dsd)$" -exec mv -vnt ${dw}/aud {} +
+
+            handle_archive ${dw}/archive
 
             rmdir ${dw}/{img,archive} 2> /dev/null&
         ;;
